# Generated by Django 3.2 on 2022-02-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddit_blog_matt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Meddit Blog!', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
