# Generated by Django 3.2 on 2022-02-13 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meddit_blog_matt', '0006_auto_20220213_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
