# Generated by Django 3.2 on 2022-02-16 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meddit_blog_matt', '0008_remove_post_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
