# Generated by Django 3.2 on 2022-02-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddit_blog_matt', '0009_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_snippet',
            field=models.CharField(default='Click above to see more!', max_length=255),
        ),
    ]
