# Generated by Django 3.2 on 2022-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddit_blog_matt', '0010_post_blog_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_snippet',
            field=models.CharField(default='Click above to read Blog!', max_length=255),
        ),
    ]
