# Generated by Django 3.2 on 2022-02-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddit_blog_matt', '0011_alter_post_blog_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_snippet',
            field=models.CharField(max_length=255),
        ),
    ]
