# Generated by Django 3.2 on 2022-02-16 21:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meddit_blog_matt', '0012_auto_20220216_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='proxy-image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
