# Generated by Django 3.2 on 2022-02-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meddit_blog_matt', '0016_alter_comment_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
